name: portfolio
description: This is my personal portfolio

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  google_fonts: ^5.1.0
  universal_html: ^2.2.3
  url_launcher: ^6.1.12
  # url_strategy: ^0.2.0
  carousel_slider: ^4.2.1
  web_smooth_scroll: ^1.1.0
  flutter_improved_scrolling: ^0.0.3
  glowstone: ^0.0.2

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/images/github.png
    # - assets/images/facebook.png
    # - assets/images/linkedIn.png
    # - assets/images/flutter.png
    # - assets/images/java.png
    # - assets/images/python.png
    # - assets/images/khalid.png
    # - assets/images/flutter_circle.png
    # - assets/images/java_circle.png
    # - assets/images/python_circle.png
    # - assets/images/backend_icon.png
    # - assets/images/mypaylist1.png
    # - assets/images/mypaylist2.png
